config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :events

  namespace :admin do
    root to: 'events#index'

    resources :events do
      member do
        put :approve
        put :decline
      end

      collection do
        get :pending
      end
    end

    resources :admins
    resources :tags
  end

  root to: 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
  include AASM

  aasm column: :state do
    state :pending, initial: true
    state :approved, :declined

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :decline do
      transitions from: :pending, to: :declined
    end
  end

  belongs_to :user
  acts_as_taggable_on :tags
  validates :title, presence: { message: :invalid_title }
  validates :organizer_email, format: {
    with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i,
    message: :invalid_email
  }, allow_blank: true
  validates :organizer_telegram, format: { with: /@.+/i,
                                           message: :invalid_telegram },
                                 allow_blank: true
  validate :start_before_end
  paginates_per 10

  def start_before_end
    errors.add(:start_time, :start_before_end) if start_time > end_time
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  before_action :authenticate_admin!
  before_action :find_event, except: [:index, :pending]
  after_action :is_authorized, except: [:new]

  def index
    @events = Event.order(:start_time).page params[:page]
  end

  def pending
    @events = Event.order(:start_time).pending.page params[:page]
  end

  def edit; end

  def show; end

  def update
    if @event.update(event_params)
      redirect_to admin_event_path, notice: t('events.notice.edit')
    else
      render 'edit'
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to admin_events_path, notice: t('events.notice.delete')
  end

  def approve
    @event.approve!
    redirect_to admin_events_path, notice: t('events.notice.approved')
  end

  def decline
    @event.decline!
    redirect_to admin_events_path, notice: t('events.notice.declined')
  end

  private

  def event_params
    params.require(:event).permit(:title,
                                  :description,
                                  :location,
                                  :start_time,
                                  :end_time,
                                  :organizer_email,
                                  :organizer_telegram,
                                  :link,
                                  :state)
  end

  def find_event
    @event = Event.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_event, only: [:edit, :show, :update, :destroy]
  before_action :check_approve, only: [:edit, :show, :update, :destroy]

  def index
    @events = current_user.events.order(:start_time).approved.page params[:page]
  end

  def new
    @event = Event.new
    @tags = Tag.pluck(:name)
  end

  def edit
    @event = current_user.events.approved.find(params[:id])
  end

  def create
    if EventService::Create.call(current_user, event_params)
      redirect_to events_path, notice: t('events.notice.new')
    else
      render 'new'
    end
  end

  def show; end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: t('events.notice.edit')
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: t('events.notice.delete')
  end

  private

  def event_params
    params.require(:event).permit(:title,
                                  :description,
                                  :location,
                                  :start_time,
                                  :end_time,
                                  :organizer_email,
                                  :organizer_telegram,
                                  :link,
                                  tag_list: [])
  end

  def find_event
    @event = current_user.events.approved.find(params[:id])
  end

  def check_approve
    redirect_to events_path, notice: t('events.notice.no_acces') if @event.pending? || @event.declined?
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<%= simple_form_for [:admin, @event] do |f| %>
  <%= f.input :title %>
  <%= f.input :description, as: :text%>
  <%= f.input :location%>
  <%= f.input :start_time, as: :datetime %>
  <%= f.input :end_time, as: :datetime %>
  <%= f.input :organizer_email %>
  <%= f.input :organizer_telegram %>
  <%= f.input :link %>
  <%= f.button :submit %>
<% end %>

app/views/admin/events/_table.html.erb
<table>
  <tr>
    <th><%= t('simple_form.labels.title') %></th>
    <th><%= t('simple_form.labels.description') %></th>
    <th><%= t('simple_form.labels.location') %></th>
    <th><%= t('simple_form.labels.user_id') %></th>
    <th><%= t('simple_form.labels.start_time') %></th>
    <th><%= t('simple_form.labels.end_time') %></th>
    <th><%= t('simple_form.labels.organizer_email') %></th>
    <th><%= t('simple_form.labels.organizer_telegram') %></th>
    <th><%= t('simple_form.labels.link') %></th>
    <th><%= t('simple_form.labels.state') %></th>
    <th></th>
  </tr>

  <% @events.each do |event| %>
    <tr>
      <td><%= link_to event.title, admin_event_path(event) %></td>
      <td><%= event.description %></td>
      <td><%= event.location %></td>
      <td><%= event.user_id%></td>
      <td><%= event.start_time %></td>
      <td><%= event.end_time %></td>
      <td><%= event.organizer_email %></td>
      <td><%= event.organizer_telegram %></td>
      <td><%= link_to event.link, event.link %></td>
      <td><%= event.state %></td>
      <td><%= link_to t('events.button.show'), admin_event_path(event) %></td>
      <td><%= link_to t('events.button.edit'), edit_admin_event_path(event) %></td>
      <td><%= button_to t('events.button.delete'), admin_event_path(event),
              method: :delete%></td>
      <td><%= button_to t('events.button.approve'), approve_admin_event_path(event), method: :put %></td>
      <td><%= button_to t('events.button.decline'), decline_admin_event_path(event), method: :put %></td>
    </tr>
  <% end %>
</table>

app/views/admin/events/edit.html.erb
<h1><%= t('events.header.edit')%></h1>
<%= render 'form' %>
<%= link_to t('events.button.back'), admin_events_path %>

app/views/admin/events/index.html.erb
<h1><%= t('events.header.all') %></h1>
<td><%= button_to t('admins.button.sign_out'), destroy_admin_session_path,
              method: :delete%></td>
<%= link_to t('events.button.pending'), pending_admin_events_path %>
<%= link_to t('admins.button.admin_users'), admin_admins_path %>
<%= link_to t('admins.button.tags'), admin_tags_path %>

<%= render 'table' %>

<%= paginate @events %>

app/views/admin/events/pending.html.erb
<h1><%= t('events.header.pending') %></h1>

<%= render 'table' %>

<%= paginate @events %>

app/views/admin/events/show.html.erb
<p>
  <strong><%= t('simple_from.labels.title') %>:</strong>
  <%= @event.title %>
</p>

<p>
  <strong><%= t('simple_from.labels.description') %>:</strong>
  <%= @event.description %>
</p>

<p>
  <strong><%= t('simple_from.labels.location') %>:</strong>
  <%= @event.location %>
</p>

<p>
  <strong><%= t('simple_from.labels.user_id') %>:</strong>
  <%= @event.user_id %>
</p>

<p>
  <strong><%= t('simple_from.labels.start_time') %>:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong><%= t('simple_from.labels.end_time') %>:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong><%= t('simple_from.labels.organizer_email') %>:</strong>
  <%= @event.organizer_email %>
</p>

<p>
  <strong><%= t('simple_from.labels.organizer_telegram') %>:</strong>
  <%= @event.organizer_telegram %>
</p>

<p>
  <strong><%= t('simple_from.labels.link') %>:</strong>
  <%= link_to @event.link, @event.link %>
</p>

<p>
  <strong><%= t('simple_from.labels.tags') %>:</strong>
  <%= @event.tag_list %>
</p>

<p>
  <strong><%= t('simple_from.labels.status') %>:</strong>
  <%= @event.state %>
</p>

<%= button_to t('events.button.approve'), approve_admin_event_path, method: :put %>
<%= button_to t('events.button.decline'), decline_admin_event_path, method: :put %>
<br>
<%= link_to t('events.button.edit'), edit_admin_event_path(@event) %> 
<%= link_to t('events.button.back'), admin_events_path %>