config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :events

  namespace :admin do
    root to: 'events#index'

    resources :events do
      member do
        put :approve
        put :decline
      end

      collection do
        get :pending
      end
    end

    resources :admins
    resources :tags
  end

  root to: 'events#index'
end

app/models/tag.rb
class Tag < ActsAsTaggableOn::Tag
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController
  before_action :authenticate_admin!
  before_action :find_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def show; end

  def edit; end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to admin_tags_path, notice: t('tags.notice.tag_created')
    else
      render 'new'
    end
  end

  def update
    if @tag.update(tag_params)
      redirect_to admin_tags_path, notice: t('tags.notice.tag_edited')
    else
      render 'edit'
    end
  end

  def destroy
    @tag.destroy
    redirect_to admin_tags_path, notice: t('tags.notice.tag_deleted')
  end

  private

  def tag_params
    params.require(:tag).permit(:name,
                                :keywords)
  end

  def find_tag
    @tag = Tag.find(params[:id])
  end
end

app/views/admin/tags/edit.html.erb
<%= simple_form_for [:admin, @tag] do |f| %>
  <%= f.input :name %>
  <%= f.input :keywords %>
  <%= f.button :submit %>
<% end %>

<%= link_to t('tags.button.back'), admin_tags_path %>

app/views/admin/tags/index.html.erb
<%= link_to t('tags.button.new'), new_admin_tag_path %>
<table>
  <tr>
    <th><%= t('simple_form.labels.name') %></th>
    <th><%= t('simple_form.labels.keywords') %></th>
  </tr>

  <% @tags.each do |tag| %>
    <tr>
      <td><%= tag.name %></td>
      <td><%= tag.keywords %></td>
      <td><%= link_to t('tags.button.show'), admin_tag_path(tag) %></td>
      <td><%= link_to t('tags.button.edit'), edit_admin_tag_path(tag) %></td>
      <td><%= button_to t('tags.button.delete'), admin_tag_path(tag),
              method: :delete%></td>
    </tr>
  <% end %>
</table>

app/views/admin/tags/new.html.erb
<%= simple_form_for [:admin, @tag] do |f| %>
  <%= f.input :name %>
  <%= f.input :keywords %>
  <%= f.button :submit %>
<% end %>
<%= link_to t('tags.button.back'), admin_tags_path %>

app/views/admin/tags/show.html.erb
<p>
  <strong><%= t('simple_from.labels.name') %>:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong><%= t('simple_from.labels.keywords') %>:</strong>
  <%= @tag.keywords %>
</p>

<%= link_to t('tags.button.edit'), edit_admin_tag_path(@tag) %> 
<%= link_to t('tags.button.back'), admin_tags_path %>