config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :events

  namespace :admin do
    root to: 'events#index'

    resources :events do
      member do
        put :approve
        put :decline
      end

      collection do
        get :pending
      end
    end

    resources :admins
    resources :tags
  end

  root to: 'events#index'
end

app/views/admin/admins/_form.html.erb
<%= simple_form_for [:admin, @admin] do |f| %>
  <%= f.input :email, as: :email %>
  <%= f.input :password, as: :password %>
  <%= f.input :role, as: :select, collection: Admin.aasm.states.map(&:name) %>
  <%= f.button :submit %>
<% end %>

app/views/admin/admins/edit.html.erb
<h1><%= t('admins.header.edit') %></h1>
<%= render 'form' %>
<%= link_to t('admins.button.back'), admin_admins_path %>

app/views/admin/admins/index.html.erb
<h1><%= t('admins.header.index') %></h1>
<td><%= button_to t('admins.button.sign_out'), destroy_admin_session_path,
              method: :delete%></td>

<%= link_to t('admins.button.new'), new_admin_admin_path %>

<table>
  <tr>
    <th><%= t('admins.label.id') %></th>
    <th><%= t('admins.label.email') %></th>
    <th><%= t('admins.label.role') %></th>
    <th></th>
  </tr>

  <% @admins.each do |admin| %>
    <tr>
      <td><%= admin.id %></td>
      <td><%= link_to admin.email, admin_admin_path(admin) %></td>
      <td><%= admin.role %></td>
      <td><%= link_to t('admins.button.show'), admin_admin_path(admin) %></td>
      <td><%= link_to t('admins.button.edit'), edit_admin_admin_path(admin) %></td>
      <td><%= button_to t('admins.button.delete'), admin_admin_path(admin),
              method: :delete%></td>
    </tr>
  <% end %>
</table>

app/views/admin/admins/new.html.erb
<h1><%= t('admins.header.new') %></h1>
<%= render 'form' %>
<%= link_to t('admins.button.back'), admin_admins_path %>

app/views/admin/admins/show.html.erb
<p>
  <strong><%= t('admins.label.id') %>:</strong>
  <%= @admin.id %>
</p>

<p>
  <strong><%= t('admins.label.email') %>:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong><%= t('admins.label.role') %>:</strong>
  <%= @admin.role %>
</p>

<%= link_to t('admins.button.back'), admin_admins_path %>
<%= link_to t('admins.button.edit'), edit_admin_admin_path %>